on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libopenblas-dev
      - name: Setup CMake
        working-directory: ${{github.workspace}}/build
        run: cmake ..
      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: make test
